# Generated by Django 5.2.17 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataBankEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_type", models.CharField(choices=[("role", "Role"), ("project", "Project"), ("achievement", "Achievement"), ("education", "Education"), ("certification", "Certification"), ("other", "Other")], db_index=True, max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("raw_text", models.TextField()),
                ("metrics", models.JSONField(default=dict)),
                ("tags", models.JSONField(db_index=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-start_date", "-created_at"]},
        ),
        migrations.AddIndex(
            model_name="databankentry",
            index=models.Index(fields=["entry_type", "is_current"], name="core_databa_entry_t_46da9f_idx"),
        ),
        migrations.AddIndex(
            model_name="databankentry",
            index=models.Index(fields=["start_date", "end_date"], name="core_databa_start_d_b3716d_idx"),
        ),
    ]
